### ISSUE TITLE
Application crashes when project name is not given

### ISSUE THREAD

**Issue by AlexVanLeyen** [realdecoy/rdvue#53]
Version: 0.6.0
Steps to reproduce:

1. In the terminal, issue the following command: `rdvue generate project`
2. When the prompt for the project name comes up, press enter.

Expected behavior:
Expected complaint of lack of name, or project created using the current parent folder's name. (similar to npm init)

Actual behavior:
```plaintext
? Please enter the name for the generated project. (e.g. my-project) Run-async wrapped function (sync) returned a promise but async() callback must be executed to resolve.
(node:7920) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at InputPrompt.onError (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\inquirer\lib\prompts\input.js:95:35)
    at SafeSubscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeUntilSubscriber.Subscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:89:26)
    at TakeUntilSubscriber.Subscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:66:18)
    at FilterSubscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\operators\filter.js:52:30)
    at FilterSubscriber.Subscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:66:18)
    at RefCountSubscriber.Subscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:89:26)
    at RefCountSubscriber.Subscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Subject.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:89:26)
    at ConnectableSubscriber.Subscriber.next (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\Users\AVanLeyen\AppData\Roaming\npm\node_modules\rdvue\node_modules\rxjs\internal\operators\mergeMap.js:95:26)
(node:7920) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with 
.catch(). (rejection id: 2)
(node:7920) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andre-vidal** [comment]
Issue resolved in version 2
